ALTER TABLE focus_logs
  ADD COLUMN IF NOT EXISTS ear FLOAT NULL AFTER is_drowsy,
  ADD COLUMN IF NOT EXISTS neck_angle FLOAT NULL AFTER ear,
  ADD COLUMN IF NOT EXISTS shoulder_diff FLOAT NULL AFTER neck_angle,
  ADD COLUMN IF NOT EXISTS head_yaw FLOAT NULL AFTER shoulder_diff,
  ADD COLUMN IF NOT EXISTS head_pitch FLOAT NULL AFTER head_yaw,
  ADD COLUMN IF NOT EXISTS face_detected INT NULL AFTER head_pitch,
  ADD COLUMN IF NOT EXISTS phone_detected INT NULL AFTER face_detected,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER phone_detected;
